---
version: 0.2

phases:
  pre_build:
    commands:
      - echo "Installing jq..."
      - curl -qL -o jq https://stedolan.github.io/jq/download/linux64/jq && chmod +x ./jq
      - echo "Installing HashiCorp Packer..."
      - export packer_url=$(curl https://releases.hashicorp.com/index.json | ./jq '{packer}' | egrep "linux.*amd64" | sort --version-sort -r | head -1 | awk -F[\"] '{print $4}')
      - echo ${packer_url}
      - curl -o packer.zip $packer_url && unzip packer.zip
      - echo "Validating Packer file"
      - ./packer validate packer_cis.json
  build:
    commands:
      - echo "Building HashiCorp Packer template"
      - ./packer build -color=false packer_cis.json | tee build.log
  post_build:
    commands:
        - egrep "${AWS_REGION}\:\sami\-" build.log | cut -d' ' -f2 > ami_id.txt
        # Packer doesn't return non-zero status; we must do that if Packer build failed
        - test -s ami_id.txt || exit 1
        - sed -i.bak "s/<<AMI-ID>>/$(cat ami_id.txt)/g" ami_builder_event.json
        - aws events put-events --entries file://ami_builder_event.json
        - echo "HashiCorp Packer build completed on `date`"
artifacts:
  files:
    - ami_builder_event.json
    - build.log
  discard-paths: yes