---

# Have found that installation often stalls in freshclam
# to avoid this, download signatures from artefactual-labs repo instead
# (freshclam daemon will update to latest signatures at a later time)

#- name: "Download clamav signatures"
#  command: "freshclam"

# Check if clamav files exist already

- stat:
    path: "/var/lib/clamav/bytecode.cvd"
  register: "clamf1"

- stat:
    path: "/var/lib/clamav/bytecode.cld"
  register: "clamf1a"

- stat:
    path: "/var/lib/clamav/daily.cvd"
  register: "clamf2"

- stat:
    path: "/var/lib/clamav/daily.cld"
  register: "clamf2a"

- stat:
    path: "/var/lib/clamav/main.cvd"
  register: "clamf3"

- stat:
    path: "/var/lib/clamav/main.cld"
  register: "clamf3a"

- set_fact:
    clamav_download: "{{ not ( ( clamf1.stat.exists or clamf1a.stat.exists ) and
                               ( clamf2.stat.exists or clamf2a.stat.exists ) and
                               ( clamf3.stat.exists or clamf3a.stat.exists ) ) }}"

- debug:
    msg: "Need to download clamav signatures"
  when: clamav_download

- name: "Get clamav signatures from artefactual-labs repo"
  git:
    repo: "https://github.com/artefactual-labs/clamav-files.git"
    dest: "/tmp/clamav-files"
  when: clamav_download

- name: "Copy clamav signatures to /var/lib/clamav"
  command: "cp /tmp/clamav-files/{{ item }} /var/lib/clamav/"
  become: yes
  with_items:
    - "bytecode.cvd"
    - "daily.cvd"
    - "main.cvd"
  when: clamav_download

- name: "Set user ownership for clamav files"
  file:
    path: "/var/lib/clamav"
    owner: "clamupdate"
    group: "clamupdate"
    state: "directory"
    recurse: "yes"
  when:
    - clamav_download