# Standards: 0.11
---

# 5.4.1.4 Ensure inactive password lock is 30 days or less

- name: 5.4.1.4 - Obtain a list of user accounts
  shell: "egrep ^[^:]+:[^\\!*] /etc/shadow | cut -d: -f1"
  register: egrep_5_4_1_4
  check_mode: no
  changed_when: False
  tags:
    - level-1
    - section-5
    - "5.4.1.4"
    - scored

- name: 5.4.1.4 - Ensure inactive password lock is 30 days or less
  lineinfile:
    dest: "/etc/default/useradd"
    regexp: "^INACTIVE\\s+"
    line: "INACTIVE={{ cis_pass_inactive_lock }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.4"
    - scored

- name: 5.4.1.4 - Set inactive password lock for all user accounts
  command: "chage --inactive {{ cis_pass_inactive_lock }} {{ item }}"
  with_items: "{{ egrep_5_4_1_4.stdout_lines }}"
  tags:
    - level-1
    - section-5
    - "5.4.1.4"
    - scored
