# tasks file for sysdig (CentOS specific)

- name: Download Draios GPG key
  rpm_key: >
    key=https://s3.amazonaws.com/download.draios.com/DRAIOS-GPG-KEY.public
    state=present
  tags: sysdig

- name: Configure Draios YUM repository
  template: >
    src=draios.repo.j2
    dest=/etc/yum.repos.d/draios.repo
    owner=root
    group=root
    mode=0644
  tags: sysdig

- name: Install sysdig packages
  yum: name={{ item }} state=present
  with_items: sysdig_packages
  tags: sysdig