---
###########################################################################
# INSTALLATION                                                            #
###########################################################################
- name: "Install packages for OSSEC agent"
  action: >
    {{ ansible_pkg_mgr }} name={{ item }} state=present update_cache=yes
  with_items:
    - gcc
    - httpd
    - telnet
  become: true

- name: "Ensure OSSEC src directory exists."
  file:
    path: "{{ ossec_install_dir }}"
    state: directory

- name: "Ensure tmp for OSSEC directory exists."
  file:
    path: "{{ ossec_tmp_dir }}/{{ ossec_untar_dir }}"
    state: directory


- name: "Download OSSEC-HIDS"
  get_url:
    url: "{{ ossec_url }}/{{ ossec_version }}.tar.gz"
    dest: "{{ ossec_tmp_dir }}/{{ ossec_tarball }}"

- name: "Download OSSEC-HIDS ASC."
  get_url:
    url: "https://github.com/ossec/ossec-hids/releases/download/{{ossec_version}}/ossec-hids-{{ossec_version}}.tar.gz.asc"
    dest: "{{ ossec_tmp_dir }}/{{ ossec_tarball }}.asc"

- name: "Download OSSEC-HIDS archive key."
  get_url:
    url: "https://ossec.github.io/files/OSSEC-ARCHIVE-KEY.asc"
    dest: "{{ ossec_install_dir }}/OSSEC-ARCHIVE-KEY.asc"

- name: "Import the OSSEC Archive Key"
  shell: gpg --import {{ ossec_install_dir }}/OSSEC-ARCHIVE-KEY.asc

# TODO Fix the checksum
#- name: "Verify OSSEC ASC"
#  shell: gpg --verify {{ ossec_tmp_dir }}/ossec-hids-{{ ossec_version }}.tar.gz.asc {{ ossec_tmp_dir }}/{{ ossec_version }}.tar.gz

- name:  "Extract OSSEC "
  unarchive:
    src: "{{ ossec_tmp_dir }}/{{ ossec_tarball }}"
    dest: "{{ ossec_tmp_dir }}"

#tar xfz ossec-hids-${ossec_version}.tar.gz
#cd ossec-hids-${ossec_version}
#cp /home/admin/ossec_preloaded-vars.conf ./etc/preloaded-vars.conf
#cat ./etc/preloaded-vars.conf#
#sudo bash ./install.sh
#sudo /var/ossec/bin/ossec-control start

- name: "OSSEC add the preloaded config file"
  template:
    src: templates/preloaded-vars.conf.j2
    dest: "{{ ossec_tmp_dir }}/{{ ossec_untar_dir }}/etc/preloaded-vars.conf"

- name: "Build / Install the agent"
  command: ./install.sh chdir={{ ossec_tmp_dir }}/{{ ossec_untar_dir }}

###########################################################################
# CONFIGURATION                                                           #
###########################################################################

- name: "Installing the ossec-agent.conf"
  template:
    src: templates/ossec.conf.j2
    dest: "{{ ossec_install_dir }}/etc/ossec.conf"
  notify:
    - ossec - restart agent
  tags: ossec

- name: "Configure the agent internal_options.conf"
  template:
    src: templates/internal_options.conf.j2
    dest: "{{ ossec_install_dir }}/etc/internal_options.conf"
  notify:
    - ossec - restart agent
  tags: ossec


# Configure the agent internal_options.conf (override per-host if
# needed)
- name: ossec - configure the agent (internal_options.conf)
  template: dest={{ ossec.install_dir }}/etc/internal_options.conf
            owner=root
            group=ossec
            mode=0440
            backup=yes
  first_available_file:
    - "{{ ansible_hostname }}_internal_options.conf.j2"
    - internal_options.conf.j2
  notify:
    - ossec - restart agent
  tags: ossec

# Patch the init.d script since it has a broken status setup
- name: ossec - configure the agent (init.d script)
  template: dest=/etc/init.d/ossec
            owner=root
            group=ossec
            mode=0755
  first_available_file:
    - "{{ ansible_hostname }}_ossec-init-script.j2"
    - ossec-init-script.j2
  tags: ossec

# Setup the client.keys file for the agent (NOTE: this requires the md5
# jinja filter to be available
- name: ossec - configure the agent key
  template: dest={{ ossec.install_dir }}/etc/client.keys
            owner=ossec
            group=ossec
            mode=0644
            backup=yes
  first_available_file:
    - "{{ ansible_hostname }}_client.keys.j2"
    - client.keys.j2
  register: client_key
  notify:
    - ossec - restart agent
  tags: ossec

# Ensure the services are started
- name: ossec - start ossec
  service: name=ossec state=started pattern=ossec
  tags: ossec

###########################################################################
# CLEANUP                                                                 #
###########################################################################

# Remove compiler components only if we added them initially
- name: ossec - remove compiler components (if necessary)
  apt: pkg=build-essential state=absent purge=yes
  when: compiler.changed
  tags: ossec

# Autoremove additional packages added if we added them initially
- name: ossec - autoremove additional components (if necessary)
  command: /usr/bin/apt-get -y --purge autoremove
  when: compiler.changed
  tags: ossec